#cloud-config
timezone: Asia/Tokyo
locale: en_US.UTF-8
users:
  - name: admin
    sudo: ALL=(ALL) ALL
    groups: wheel
    password: $1$hoge$zja42e4Qs10ghYZK1cWr70
    uid: 1000
    shell: /bin/bash
packages:
  - vim
package_update: true
package_upgrade: true
